### ISSUE TITLE
prioritize fails when lpsymphony is installed and Rsymphony is not [bug]

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#11]
Hi,

The `prioritize` functions fails when lpsymphony is installed and Rsymphony is not. I suspect this is due to lines 68 and 169 in "prioritize_symphony.R".

The `priorize_symphony` methods for `maxcover_model` and `minset_model` objects choose the correct function to solve the problem using this code:

```
  if (requireNamespace("Rsymphony", quietly = TRUE)) {
    symphony_solve_LP <- Rsymphony::Rsymphony_solve_LP
  } else if (requireNamespace("lpsymphony", quietly = TRUE)) {
    symphony_solve_LP <- lpsymphony::lpsymphony_solve_LP
  } else {
    stop("Neither Rsymphony nor lpsymphony are installed")
  }
```

However,  the `symphony_solve_LP` function is not used to solve the problem, and instead, the `Rsymphony::Rsymphony_solve_LP` is always used as we can see in lines 68 and 169: 

```
results <- Rsymphony::Rsymphony_solve_LP(
```

I think we just need to change these lines to use  `symphony_solve_LP`? Although I have not used either the Rysymphony or lpsymphony packages before so it may be more complicated than this (eg. different arguments, subtle nuances?).

Cheers,

Jeff

**Comment by jeffreyhanson** [comment]
I've think I've this in the bugfix/lpsymhpony branch - but I want to make sure it works before submitting a PR.

**Comment by mstrimas** [comment]
Yeah, definitely a typo on my part. Thanks for catching it!
