### ISSUE TITLE
missing data in feature rasters to denote absence [feature request]

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#12]
Hi,

I think it would be really useful to allow missing data values in the `feature` argument to the `maxcover_model` and `minset_model`. Generally, missing data values are used to indicate an absence of the feature in a pixel. Although users could set missing data values to zero, I suspect there might be performance gains to be had if the functions use missing data.

Cheers,

Jeff

**Comment by jlehtoma** [comment]
+1 for this as having missing data is fairly common. I think the `include` argument can already be used to achieve the same result (i.e. including only non-NA planning units), but allowing missing values would be slightly more convenient.

**Comment by mstrimas** [comment]
Unless @jeffreyhanson is already working on this, I can add this feature over the next couple days. Thanks for the suggestion.

**Comment by jeffreyhanson** [comment]
I haven't got to this yet, but I can probably get to this tomorrow.

**Comment by mstrimas** [comment]
Just pushed an update to add this feature. Works for both raster and vector planning units. NAs are now treated the same as zeros.

@jeffreyhanson my `summarize_features()` function calls your `calcPuVsSpeciesData()` function from the marxan package. Note that that function gives a warning if the RasterStack has NAs in it, however, in my testing it returns the correct data frame. I've just wrapped the `calcPuVsSpeciesData` call in a `suppressWarnings` for now.

**Comment by jeffreyhanson** [comment]
Awesome - thanks for adding this!
