### ISSUE TITLE
NA values in x$v of df_to_matrix [bug]

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#26]
One of the advantages of using a sparse matrix object is to avoid representing cells with `NAs` in them to reduce the amount of memory used. This will be especially useful when working with large problems. So, after running the `df_to_matrix` function cells with a NA value should be omitted from the  returned `simple_triplet_matrix`.

```
df <- data.frame(i = c(1, 1, 3), j = c(1, 3, 3), v = c(10, 20, NA))
mtx <- matrix(c(10,0,20,0,0,0,0,0,0) ncol=3, byrow=TRUE)
expect_equal(as.matrix(df_to_matrix(df))), mtx)
```

**Comment by mstrimas** [comment]
My impression is that sparse matrices are meant to reduce memory usage by omitting *zeros* not NAs. So this change essentially makes the assumption that NAs are the same as 0, which I don't think is necessarily the case. In the particular case used in this package `df_to_matrix()` is used for setting up the representation matrix where it probably makes sense to have NA -> 0, but I don't think I'd want this in general. Not sure what the best approach is then, maybe either just throwing an error or having a function parameter to control this behaviour.

**Comment by jeffreyhanson** [comment]
Yeah, that's true. Sorry, that's what I meant, I should have been more specific.

Yeah, that makes sense. I'll kill this PR and update the tests accordingly to make NA values in the output valid.
