### ISSUE TITLE
incorrect extent of result from make_grids when input needs trimming [bug]

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#34]
If a `RasterLayer` is supplied that has an entire column (or rows) containing NA values, then the `make_grid` function returns a `SpatialPolygons` object that does not align with the input `RasterLayer` object.

```
# data
rst <- raster::raster(matrix(c(1:12, NA, NA, NA, NA), 4, 4)) # raster with one column of NA values
sp <- make_grid(rst, cell_width = raster::res(rst)[1], type='square')
# test extents
expect_equal(raster::extent(sp), raster::extent(rst))
expect_equal(sum(!is.na(raster::as.matrix(rst))), length(sp@polygons))
# plot objects
sp::plot(sp) # set up canvas
raster::plot(rst, add=TRUE) # add raster
sp::plot(sp, add=TRUE) # add grid cells
``` 

![test](https://cloud.githubusercontent.com/assets/3610005/19952403/b796340c-a1b0-11e6-805e-3226bf689475.png)

**Comment by jeffreyhanson** [comment]
Wait a minute it's working now.. let me work out what I did wrong..

**Comment by jeffreyhanson** [comment]
Actually, I'm not sure if this functionality is desired. The `make_grid` function doesn't do any handling of NA values in the inputs, so maybe trimming rasters should be left up to the user as a pre-processing step, so that `make_grid` is consistent?

I'm closing this issue and the PR. If you think this should be addressed, then maybe we should also handle NA values more explicitly?

**Comment by mstrimas** [comment]
Yes, I think NAs should be handled outside of make_grid. Also, in this case it would be easier for the user to supply the planning units as a raster object, in which case the NAs cells will be removed.
