### ISSUE TITLE
Fix argument names in README.md

### ISSUE THREAD

**Issue by jlehtoma** [mstrimas/prioritizr#4]
Both of the following functions use arguments `pu` in `README.md` while correct arg name is `x`:

```
msc_model <- minsetcover_model(pu = cost, features = species, targets = 0.2)
[...] 
mc_model <- maxcover_model(pu = cost, features = species, budget = b_25)
```

`README.Rmd` already has it right, so generating the md-file should be quick (I didn't have all the solvers installed so couldn't do this).

**Comment by mstrimas** [comment]
Fixed this awhile back but forgot to close. Thanks!
