### ISSUE TITLE
Travis Failing

### ISSUE THREAD

**Issue by mstrimas** [mstrimas/prioritizr#46]
Hey @jeffreyhanson 

Travis is now failing with a fairly cryptic error: https://travis-ci.org/mstrimas/prioritizr

If you have any thoughts on how to fix this I'd appreciate it. Thanks!

**Comment by jeffreyhanson** [comment]
Hi,

It looks like there was an issue on [Travis's end](https://github.com/travis-ci/travis-ci/issues/6882), but that has now been resolved. 

I reran my fork on Travis and it [seems to work now](https://travis-ci.org/jeffreyhanson/prioritizr).

Let me know if its still not working.

**Comment by mstrimas** [comment]
Thanks!
