### ISSUE TITLE
Ready for use?

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#5]
Hi,

I want to generate prioritisations using the maximum coverage reformulation of the marxan problem, and I was wondering if this package was ready for use?

Cheers,

Jeff

**Comment by mstrimas** [comment]
Hey Jeff, yes that piece should work. Let me know how it goes. At some point I intended on adding more functionality to the package, but have been too busy recently.

Matt

**Comment by jeffreyhanson** [comment]
Awesome - will do - thanks!
