### ISSUE TITLE
thread control [feature request]

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#6]
Hi,

I was wondering if it would be possible to have explicit control over the number of threads used for solving problems? This would mean that users can specify how many threads they want to use for solving a problem rather than relying on defaults. 

The default for Gurobi is ["It will generally use all of the cores in the machine, but it may choose to use fewer"](https://www.gurobi.com/documentation/6.5/refman/threads.html). This could cause problems for users that have multiple computational processes running at once.

I suggest adding a `threads` argument to the `prioritize` function. Let me know if you don't have time for this and I'll submit a PR.

Cheers,

Jeff

**Comment by mstrimas** [comment]
Sure, that's not a bad idea. I'm not sure if any of the other packages have an option for controlling the number of threads, but I can at least add it for Gurobi.

**Comment by mstrimas** [comment]
Just pushed an update with a `threads` parameter added as requested. Currently only works for Gurobi. Thanks for the suggestion!

**Comment by jeffreyhanson** [comment]
Awesome - thanks!
