### ISSUE TITLE
Add continuous integration [enhancement]

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#7]
Hi,

You might find it useful to add in continuous integration (eg. Travis CI for Mac OSX and Ubuntu, and AppVeyor for Windows) to automatically run `devtools::check()` after each commit. I find this really useful for ensuring that my packages are up to date with the latest versions of dependencies. Also, if you plan on submitting this to CRAN then CI services can be used to demonstrate that the package passes checks on multiple platforms.

If you're not familiar with CI, here's some more info on CI:

https://www.r-bloggers.com/continuous-integration-for-r-packages/
https://www.r-bloggers.com/a-beginners-guide-to-travis-ci-for-r/

Also, just as a heads up, I plan on using this package for one of my PhD chapters, so I'm keen to help finish it off. So over the next few days, I'll be submitting issues and PRs to fix them. 

Cheers,

Jeff

**Comment by mstrimas** [comment]
I thought about this, and submitting to CRAN, but was worried Gurobi would pose a problem because (a) it's not on CRAN and (b) it requires a license. The other solvers also require installing additional software. What are your thoughts on this? Can Travis CI handle this?

**Comment by jeffreyhanson** [comment]
I don't think having gurobi under Suggests should be a problem (see [raptr](https://cran.r-project.org/web/packages/raptr/) and [cherry](https://cran.r-project.org/web/packages/cherry/index.html)).

I've been playing with build configs under my feature/ci branch over the last couple of days. 

I've got testing on Windows Server 2012 R2 working (https://ci.appveyor.com/project/jeffreyhanson/prioritizr/build/job/840aol0aay7i899m).

Travis is proving to be a bit tricky. I'll submit a PR when I've got it working for Ubuntu and OSX too.

**Comment by jeffreyhanson** [comment]
The main trick is pre-rendering the vignettes. 

Since none of the solvers will be available on CRAN, and since CRAN recompiles vignettes, we have to build the vignettes so that they are found in `inst/doc/` and then replace the `.Rmd` files in the `vignettes/` directory with dummy `.Rmd` files.

I built a [Makefile to automate this process with raptr](https://github.com/jeffreyhanson/raptr/blob/master/Makefile). Essentially, the "real" vignette `.Rmd` files live in `inst/vign`. These are copied to the `vignettes/` directory, `devtools::build_vignette()` is then run. Then all the files `vignettes/` directory are deleted, and a dummy vignette `inst/vign/placeholder.Rmd` with no R code is then copied to `vignettes/`.

**Comment by jeffreyhanson** [comment]
Also, any examples that use the solvers will have to be encapsulated in `\dontrun{}`'s.

I'll make a separate issue for making the package compatible with CRAN and make a PR that addresses this.

**Comment by jeffreyhanson** [comment]
Just to keep you in the loop, [the latest R update broke the Mac OSX CI for Travis](https://github.com/travis-ci/travis-ci/issues/6807).

I have the CI working for Ubuntu (14.04 LTS) and Windows. In theory, it should also work for Mac OSX once Travis has fixed it, but I want to hold off submitting this PR till I can verify it.

**Comment by mstrimas** [comment]
Ok, thanks for all the info! I've been meaning to learn more about Travis CI, so I look forward to your  PR

**Comment by jeffreyhanson** [comment]
It looks like it might take a while before the Mac OSX CI is up and running so I'm going to submit a PR to get Ubuntu and Windows working so we have some form of CI.

**Comment by jeffreyhanson** [comment]
After you merge the PR, you'll need to activate [Travis CI](https://travis-ci.org), [AppVeyor](https://ci.appveyor.com), and [Coveralls](https://coveralls.io/) for the repo.

Although Coveralls isn't a CI, it provides info on code test coverage which I find useful for ensuring for making sure i haven't missed anything in the unit tests.

If you visit their webpages and sign in using your GitHub credentials, you just need to find this repo and toggle it to on. After that, any commits will trigger a build attempt using these services. Generally, the builds take between 10-30 minutes.

**Comment by mstrimas** [comment]
Very cool! Thanks for adding this. There were some issues with the tests comparing data frames because the ordering was different, however everything is working fine now with the latest commit.
