### ISSUE TITLE
`RasterLayer` objects to specify locked.in and locked.out planning units [feature request]

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#8]
Hi,

I think it would be really useful if users could use `RasterLayer` objects to specify locked in and locked out planning units.

Cheers,

Jeff

**Comment by mstrimas** [comment]
I started adding this in awhile back when I was initially building the package, but wasn't sure of the best way to approach it for a UI perspective. Are you thinking of two optional binary RasterLayer objects, one for locked in and one for locked out? I think that's probably a fairly easy add.

**Comment by jeffreyhanson** [comment]
Yeah, I think two binary raster objects would be great.

**Comment by mstrimas** [comment]
Just added this feature in PR #30 . Only applied to cases where input planning units are RaserLayer objects.
