### ISSUE TITLE
enhance the full vignette? [enhancement]

### ISSUE THREAD

**Issue by jeffreyhanson** [mstrimas/prioritizr#9]
Hi,

At the the moment, the full vignette and the quickstart vignette are practically identical. I really like the idea of having a quickstart and a full vignette, so I was wondering what we could to do enhance the full vignette? Perhaps showcasing locked in and locked out options? Or generating curves showing budget vs. number of targets met using the maxcove_model?

Let me know if you have any ideas.

Cheers,

Jeff

**Comment by mstrimas** [comment]
The full vignette is another thing I didn't get around to. Once your PR for maxcover with targets is ready I can work on the vignettes. Basically, I'd have the quick start guide just cover the most basic features of the two models, and the full vignette deal with locked in/out, excluding planning units with NA, different input  formats (polygons, rasters, numeric), possibly giving the mathematical details of the models, etc.

**Comment by jeffreyhanson** [comment]
Sounds great. Let me know if you would like me to have a read over it when it's ready.

**Comment by mstrimas** [comment]
Added full vignette
